// let boxes = document.getElementsByClassName("box")
let boxes = document.querySelector(".container").children
console.log(boxes)

function get_random_color(){
    let a = 0;
    let b = 255; 
    let val1 = Math.ceil(a + Math.random()*b)
    let val2 = Math.ceil(a + Math.random()*b)
    let val3 = Math.ceil(a + Math.random()*b)
    return `rgb(${val1},${val2},${val3})`
}
// used foreach because boxes is an html collection and doesn't work as array
Array.from(boxes).forEach(e => {
    e.style.backgroundColor = get_random_color()
    e.style.color = get_random_color()
})



// setInterval --> performs a specified task repeatedly after a given amount of time interval , takes 2 inout one the function that to be executed and the interval
let a = setInterval(() => {
    Array.from(boxes).forEach(e => {
        e.style.backgroundColor = get_random_color()
        e.style.color = get_random_color()
    })
}, 200);

// clearInterval --> used to stop the interval, takes a no. as input of that interval which setInterval generates to stop it
clearInterval(a)

// setTimeout --> used similarly as setInterval but performs the given task or execute the given function on once after the given interval or time

let b = setTimeout(() => {
    Array.from(boxes).forEach(e => {
        e.style.backgroundColor = get_random_color()
        e.style.color = get_random_color()
    })
}, 6000);
//  clearTimeout --> works similarly as clearInterval but used for clearing the timeout before it happens , takes the same input as clearInterval the no. value generated by setTimeout
clearTimeout()